# -*- coding: utf-8 -*-
"""Copy of testpytorch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dBWg9nohXWZap5b5dGzIOMzk-5il6DKJ
"""

import torch

x = torch.arange(12, dtype=torch.float32)

print(x)